NEUTRON PURGE! [DNM] YET!
StarbloomSS13/StarbloomSS13 pull request #102
Opened 2022-07-18 05:11 UTC by Moltovz

## About The Pull Request
Adds an alternative to the nuke. Neutron purging will wipe out all life on the ship unless they are in `/area/maintenance/radshelter`
AOAOAOAOAOA DONT MERGE THIS YET, LOTS OF ISSUES. THIS IS AN INITIAL PR.
![image](https://user-images.githubusercontent.com/61367602/179448698-974bd44c-aa6d-41d0-b602-1d995ecd7587.png)

https://user-images.githubusercontent.com/61367602/179448773-b8eb3a0c-22a2-4e7b-9f29-ab288b0e4ee4.mp4

## Why It's Good For The Game

Requested by Sylphet and Ches
- [x] UI elements
- [x] Toggable `keycard_auth` proc
- [x] sound effect
- [x] lights turning red when purge is active
- [ ] CELLULAR DAMAGE AS TIMER TICKS DOWN
- [ ] FIX TIMER CODE ON LINE 189 `keycard_authentication.dm`
- [ ] UPDATES ON HOW MUCH TIME IS LEFT ON THE TIMER
- [ ] LESS SHIT CODE
- [ ] THREE MINUTE VERSION OF ALARM FILE, OR FIND AN EFFICIENT WAY TO LOOP IT

## Changelog
:cl:
add: UI elements for Neutron Purge
add: Custom alarm sound, by Sylphet
add: Neutron purge event.
/:cl:

2022-07-18 09:29 UTC, distributivgesetz requested changes

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +			stationlights.color = "#f3fffa" //-----this will wipe any spraypaint off of a light. Too bad!---- (VivI)
I recommend implementing a var in station lights, this is kinda oof
Example exists in tg code already

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +		for(var/obj/machinery/light/stationlights)
What list are you foreaching here?

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +			toggle_neutron_self_destruct()
I absolutely don't know how to feel about Neutron Purge to be activated by two heads of staff, since the nuke is a roundender and it usually requires an admin to grant it. @Sylphet

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +	set_security_level("[GLOB.neutron_purge? "delta" : "blue"]")
Sec level defines here

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +		if(istype(victim.loc, /area/maintenance/radshelter))
`target_turf.loc`

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +				shelter = TRUE //u winnner
?

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +		SSticker.roundend_check_paused = TRUE
This prevents the round from ending, why not use `force_ending` here?

2022-07-18 09:29 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +		if(victim.stat != DEAD && target_turf && is_station_level(target_turf.z)) //is target_turf on the station Zlevel? If not, dont dust them
Technically we can dust everyone regardless of being dead, right?

2022-07-18 09:34 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +		priority_announce("ATTENTION NEUTRON PURGE PROTOCOL COMMENCING. ALL STAFF ARE ADVISED TO RETREAT TO A RADIATION SHELTER. PURGE COMMENCING IN [neutron_death] SECONDS. THIS IS NOT A DRILL.", "Purge P
Write a define for a time and use time2text here

2022-07-18 09:37 UTC, distributivgesetz commented on code/modules/security_levels/keycard_authentication.dm
> +		priority_announce("ATTENTION NEUTRON PURGE PROTOCOL COMMENCING. ALL STAFF ARE ADVISED TO RETREAT TO A RADIATION SHELTER. PURGE COMMENCING IN [neutron_death] SECONDS. THIS IS NOT A DRILL.", "Purge P
Make a define for a duration in seconds and use time2text here

2022-07-18 10:34 UTC, distributivgesetz commented
@Cheshify we need radshelters on northpoint if this goes through

2022-07-18 15:37 UTC, distributivgesetz commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                      color="red"
I'd say make this standard blue button, red buttons are more like "pay attention to me" buttons, eg confirms

2022-07-18 15:39 UTC, distributivgesetz commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                      color="red"
this is completely optional styling, if you want to keep the styling then just leave it as it is

2022-07-18 15:40 UTC, Moltovz commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                      color="red"
Sylph said themself that they'd prefer the button be red, albeit a darker shade in the final version.

2022-07-18 15:42 UTC, distributivgesetz commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                      color="red"
i'm very much on the fence about it being on a KAD still
could you add admin logging and a way to cancel purges through a log?

2022-07-18 16:45 UTC, Moltovz commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                      color="red"
Sure thing

2022-07-19 04:14 UTC, Moltovz commented on code/modules/security_levels/keycard_authentication.dm
> +	neutron_death = addtimer(CALLBACK(GLOBAL_PROC, .proc/neutron_destruct), GLOB.neutron_purge? 300 SECONDS : deltimer())
ok trust me, this works. well. `addtimer(CALLBACK(GLOBAL_PROC, .proc/neutron_destruct), GLOB.neutron_purge? 300 SECONDS : qdel(neutron_death))` does. Deltimer doesnt, mixed vars up.

2022-07-19 13:39 UTC, Moltovz commented
> @Cheshify we need radshelters on northpoint if this goes through

But they can't buy extension I think for flavor radiation shelters shouldn't be connected to the vent/scrubber Network. Think like viro. A canister for contaminants and an air canister wrenched outside of it.

2022-07-23 12:04 UTC, distributivgesetz commented
fyi (since this is still a draft): please don't use one-line ifs if it's not going to be used as an expression, that's typically bad style

2022-08-25 01:16 UTC, closed without merging